name: Maven Package

on:
  release:
    types: [created]
  workflow_dispatch: # permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      # 1. Checkout do código
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configuração do Java (JDK 11)
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      # 3. Build do projeto com Maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      # 4. Deploy para GitHub Packages
      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 5. Upload de artefatos (opcional, útil para debug ou download manual)
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: maven-artifact
          path: target/*.jar
